### ISSUE TITLE
Migration to new bexio IdP for all API clients

### ISSUE THREAD

**Issue by simoor** [christianruhstaller/bexio-api-php-client#17]
Bexio will replace its identity provider (IdP) over the course of the next six months. The identity provider https://idp.bexio.com will be shut down on 31.03.2025.

It's needed to migrate to auth.bexio.com. The detailed instructions to migrate to the new IdP can be found on https://docs.bexio.com/#section/Authentication/Migration-from-idp.bexio.com-to-auth.bexio.com

**Comment by simoor** [comment]
created MR. @christianruhstaller please merge

**Comment by christianruhstaller** [comment]
This repository is not really active anymore. I would suggest to use the repository from onlime https://github.com/onlime/bexio-api-client
