### ISSUE TITLE
More Options (Projects etc.)

### ISSUE THREAD

**Issue by rorych** [christianruhstaller/bexio-api-php-client#4]
Love your Package! Thanks for the great work.

I would like to use it for the contacts and the projects.
There doesn't seem to be a "Project.php" File in the Resource Folder.

Is that something that you are working on?
I'm trying to extend it myself, by manipulating your code, but if you could offer a update, with the necessary changes, i would be very grateful!

Thanks in advance for your response

**Comment by christianruhstaller** [comment]
Thanks. 
I'm currently not working actively on this project. For now I don't have the time but the idea is for sure to extend it, so the whole API is implemented. 

I will have a look into it and maybe I will implement it in the next few days.

As long as it's not implemented you can use the functions from Client to call the resources: get, post, put, delete.

**Comment by rorych** [comment]
Ah, i didn't think of that, yeah cool! 
In that case, i'll try it with the direct get statement, thanks!
