### ISSUE TITLE
Order search API endpoint

### ISSUE THREAD

**Issue by aarsla** [christianruhstaller/bexio-api-php-client#5]
Per https://docs.bexio.com/ressources/kb_order/#search-orders should be POST, not GET:

Order.php line 27:  
`return $this->client->get('kb_order/search', $params);`
should be
` return $this->client->post('kb_order/search', $params);`

**Comment by aarsla** [comment]
Same goes for Invoice...
#6

**Comment by christianruhstaller** [comment]
Your pull request is merged.
